### ISSUE TITLE
custom height not working in heightforrow.

### ISSUE THREAD

**Issue by Premal-Khetani** [chika-kasymov/UITextField_AutoSuggestion#1]
Hello, 
Its great library for auto complete. 

Well i used it with my custom cell as well as custom layout. now i used below code for height : 
```
func autoSuggestionField(_ field: UITextField!, tableView: UITableView!, heightForRowAt indexPath: IndexPath!, forText text: String!) -> CGFloat {
        return 100
    }
```
but it doesn't working. could you please help me out for it. 

Thanks

**Comment by chika-kasymov** [comment]
Hi, @Premal-Khetani!

I did a small fix and now your code should work. The only thing you need to do is to update the library to **0.2.1** version.

**Comment by Premal-Khetani** [comment]
@chika-kasymov Thanks for the Quick fix 👍
