### ISSUE TITLE
Add min character length before showing suggestions

### ISSUE THREAD

**Issue by vladasdrejeris** [chika-kasymov/UITextField_AutoSuggestion#2]
Hi, 

Could you add a property that would allow to control that suggestions are displayed only when user enters a specified number of characters?

**Comment by chika-kasymov** [comment]
Hi @vladasdrejeris,

This and other issue opened by you make sense. Unfortunately, I don't have time on these weekdays to work on that. Let me add a reminder to this weekends to add these features.

Note, you can always make a pull request if this is urgent ;)

**Comment by vladasdrejeris** [comment]
Thanks for a quick reply, maybe I will make a pull request :)

**Comment by chika-kasymov** [comment]
@vladasdrejeris please, check the updated version. I added this commit ([#1b894bb](https://github.com/chika-kasymov/UITextField_AutoSuggestion/commit/1b894bb0ff08711afa21c84b20ab852d250d59a2)) which should solve your problem.
