### ISSUE TITLE
Show nothing instead of "No matches" when there are no suggestions

### ISSUE THREAD

**Issue by vladasdrejeris** [chika-kasymov/UITextField_AutoSuggestion#3]
Hi, 

Is it possible to show nothing when there are no suggestions instead of "No matches" text?
I would like to show suggestions only if there is something to display.

**Comment by chika-kasymov** [comment]
@vladasdrejeris can you provide details about how you see the working solution?

If you state to show nothing as to not show alpha view and suggestions table view then there is one problem to implement a good solution for this issue. For example, if we don't show anything user will be able to scroll. Then a text field may be out of the screen when user will enter some word(s) which should return and show a list of suggestions.

If you state to show anything except alpha view then from my opinion it's bad UI experience. I provided a way to add a custom empty view ([#6089657](https://github.com/chika-kasymov/UITextField_AutoSuggestion/commit/6089657a82c87197d95a94e104a237d67620498e)) which may solve your problem partially.
