### ISSUE TITLE
Scrolling the linked TextField up doesn't scroll up the suggestions

### ISSUE THREAD

**Issue by JohnnyBaggins** [chika-kasymov/UITextField_AutoSuggestion#4]
I'm currently facing an issue I can't seem to solve.
I have a text field on an interface of which the keyboard would cover the suggestions once the keyboard comes in. In order to prevent that, the ScrollView on which the TextField is placed gets scrolled up by the keyboard's size when the keyboard comes in. Once I type, the suggestions are shown and all is nice and clean. But if I now leave the TextField (e.g. by pressing Return) and enter the text field again, suddenly my suggestions _don't_ scroll up anymore and get displayed where the  TextField _was_, rather than where it _is_.

I tried to move the TableView of the TextField, as well as the TableViewContainerView, but neither seems to have any effect. Am I overlooking something or is this behaviour simply a bug that's currently not fixed?

**Comment by chika-kasymov** [comment]
Hi, @JohnnyBaggins! Can you capture a small video/gif of that issue?

**Comment by JohnnyBaggins** [comment]
Hi, I'll close this. I'm not entirely sure what I had been doing wrong, but I must have misused some part of the framework because after kicking the framework out and re-running pod install and all that good stuff, it somehow worked cleanly. Excuse the inconvenience.
